[tool.poetry]
name = "luigiflow"
version = "0.1.0"
description = ""
authors = ["Wataru Hirota <wataru@whiro.me>"]

[tool.poetry.dependencies]
python = "^3.9"
luigi = "^3.0.3"
mlflow = "^1.22.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
