[tool.poetry]
name = "luigiflow"
version = "0.1.0"
description = ""
authors = ["Wataru Hirota <wataru@whiro.me>"]

[tool.poetry.dependencies]
python = "^3.9"
luigi = "^3.0.3"
mlflow = "^1.22.0"
isort = "^5.10.1"
pandas = "^1.3.5"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
mypy = "^0.920"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39']
include = '\.pyi?$'
extend-exclude = 'luigiflow/testing.py'

[tool.mypy]
ignore_missing_imports = true
